# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-04-19 02:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminMan',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='超管主键')),
                ('adminName', models.CharField(max_length=30, unique=True, verbose_name='超管姓名')),
                ('password', models.CharField(max_length=100, verbose_name='超管密码')),
            ],
            options={
                'db_table': 't_admin',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='AsSchedule',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='课程主键')),
                ('courseName', models.CharField(max_length=30, unique=True, verbose_name='课程名')),
            ],
            options={
                'db_table': 't_as_schedule',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='班级主键')),
                ('className', models.CharField(max_length=30, unique=True, verbose_name='班级名称')),
            ],
            options={
                'db_table': 't_class',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='课程主键')),
                ('course', models.CharField(max_length=30, unique=True, verbose_name='课程名')),
                ('desc', models.TextField(verbose_name='课程描述')),
            ],
            options={
                'db_table': 't_course',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='成绩主键')),
                ('score', models.CharField(blank=True, max_length=20, null=True, verbose_name='学生成绩')),
            ],
            options={
                'db_table': 't_score',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SelectCourse',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='选课主键')),
                ('selCourse1', models.CharField(max_length=30, unique=True, verbose_name='课程名1')),
                ('selCourse2', models.CharField(max_length=30, unique=True, verbose_name='课程名2')),
                ('selCourse3', models.CharField(max_length=30, unique=True, verbose_name='课程名3')),
                ('selCourse4', models.CharField(max_length=30, unique=True, verbose_name='课程名4')),
            ],
            options={
                'db_table': 't_select_course',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='学生主键')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='学生姓名')),
                ('password', models.CharField(max_length=100, verbose_name='学生密码')),
                ('age', models.IntegerField(blank=True, null=True, verbose_name='学生年龄')),
                ('gender', models.CharField(default='男', max_length=6, verbose_name='学生性别')),
                ('enter_date', models.DateTimeField(auto_now_add=True, verbose_name='入学时间')),
                ('photo', models.ImageField(default='static/img/stu.jpg', upload_to='static/img/photo', verbose_name='学生照片')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='上次登录时间')),
                ('remark', models.TextField(verbose_name='备注信息')),
                ('classId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='studentCMS.Classes')),
            ],
            options={
                'db_table': 't_student',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='教师主键')),
                ('teaName', models.CharField(max_length=30, unique=True, verbose_name='教师姓名')),
                ('teaPassword', models.CharField(max_length=100, verbose_name='教师密码')),
                ('teaAge', models.IntegerField(default=20, verbose_name='教师年龄')),
                ('teaGender', models.CharField(db_column='teaSex', default='男', max_length=6, verbose_name='教师性别')),
                ('teaLast_login', models.DateTimeField(blank=True, null=True, verbose_name='上次登录时间')),
                ('teaPhoto', models.ImageField(default='static/img/tea.jpg', upload_to='static/img/photo', verbose_name='教师照片')),
                ('clsId', models.ManyToManyField(to='studentCMS.Classes')),
            ],
            options={
                'db_table': 't_teacher',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='selectcourse',
            name='stuId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='studentCMS.Student'),
        ),
        migrations.AddField(
            model_name='score',
            name='studentId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentCMS.Student'),
        ),
        migrations.AddField(
            model_name='asschedule',
            name='teaId',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='studentCMS.Teacher'),
        ),
    ]
