# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-04-22 02:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentCMS', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='age',
            field=models.IntegerField(default=18, verbose_name='学生年龄'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teaAge',
            field=models.IntegerField(default=26, verbose_name='教师年龄'),
        ),
    ]
