# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-04-22 07:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentCMS', '0002_auto_20190422_1028'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='courseId',
            field=models.ManyToManyField(to='studentCMS.Course'),
        ),
    ]
