# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-04-22 08:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentCMS', '0003_student_courseid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selectcourse',
            name='stuId',
        ),
        migrations.AddField(
            model_name='selectcourse',
            name='stuName',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='选课的人'),
        ),
        migrations.AlterField(
            model_name='selectcourse',
            name='selCourse1',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='课程名1'),
        ),
        migrations.AlterField(
            model_name='selectcourse',
            name='selCourse2',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='课程名2'),
        ),
        migrations.AlterField(
            model_name='selectcourse',
            name='selCourse3',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='课程名3'),
        ),
        migrations.AlterField(
            model_name='selectcourse',
            name='selCourse4',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='课程名4'),
        ),
    ]
